#!/usr/bin/env bash
# Usage: devbox completions <command> [arg1 arg2...]

set -e
[ -n "$DEVBOX_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  devbox-help --usage completions >&2
  exit 1
fi

# Provide devbox completions
if [ "$COMMAND" = "--complete" ]; then
  exec devbox-commands
fi

COMMAND_PATH="$(command -v "devbox-$COMMAND" || command -v "devbox-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide devbox completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
