#!/bin/bash

declare -A osInfo
osInfo[/etc/redhat-release]=yum
osInfo[/etc/arch-release]=pacman
osInfo[/etc/gentoo-release]=emerge
osInfo[/etc/SuSE-release]=zypp
osInfo[/etc/debian_version]=apt-get
osInfo[/etc/alpine-release]=apk

for f in "${!osInfo[@]}"
do
  if [[ -f $f ]];then
      pkg_manager=${osInfo[$f]}
  fi
done

case "$pkg_manager" in
  apt-get)
    sudo apt-get update
    sudo apt-get install nvtop htop speedometer rsync tmux
    ;;
  *)
    echo "Distribution not supported."
    ;;
esac
