#!/usr/bin/env bash

shell="${1:-${SHELL##*/}}"

echo "Setting history file for shell: $shell"
read -r -p "Continue (y/n)?" choice
case "$choice" in
y | Y)
  echo "export HISTFILE='${DEVBOX_ROOT}/cache/.${shell}_history'" >>"${HOME}/.${shell}rc"
  ;;
*)
  echo "Abort."
  ;;
esac
