#!/bin/bash

if ! command -v zsh 1>/dev/null 2>&1; then
  echo "devbox: zsh is not installed, can't continue" >&2
  exit 1
fi

echo "devbox: Installing Oh My Zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || exit 1

echo "devbox: Installing zplug"
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh || exit 1

echo "devbox: Writing default config for zplug to ${HOME}/.zshrc"
echo "
# >>> zplug section >>>
source ${HOME}/.zplug/init.zsh

zplug 'mafredri/zsh-async', from:github
zplug 'sindresorhus/pure', use:pure.zsh, from:github, as:theme
# zplug 'romkatv/powerlevel10k', as:theme, depth:1

zplug 'zsh-users/zsh-autosuggestions', as:plugin, defer:2
zplug 'zdharma/fast-syntax-highlighting', as:plugin, defer:2
zplug 'conda-incubator/conda-zsh-completion', as:plugin, defer:2

if ! zplug check --verbose; then
    zplug install
fi

zplug load
# <<< zplug section <<<
" >>"${HOME}/.zshrc"

# disable theme, use the theme set by Zplug
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME=""/' "${HOME}/.zshrc"

echo "devbox: Installing autojump"
# autojump
git clone https://github.com/joelthelion/autojump.git
cd autojump || exit
./install.py
cd ..
rm autojump -rf
# Enable autojump plugin
sed -i 's/plugins=(/plugins=(autojump /' "${HOME}/.zshrc"
echo "
[[ -s ${HOME}/.autojump/etc/profile.d/autojump.sh ]] && source ${HOME}/.autojump/etc/profile.d/autojump.sh
" >>"${HOME}/.zshrc"
